test: cicd

diff --git a/.github/workflows/01-get-publish-version.yml b/.github/workflows/01-get-publish-version.yml
--- a/.github/workflows/01-get-publish-version.yml
+++ b/.github/workflows/01-get-publish-version.yml
@@ -15,25 +15,14 @@ jobs:
       - name: 🔄 Init Cache
         uses: ./.github/actions/npm-cache
 
-      - name: 💃🕺 Set release or prerelease
-        run: |
-          if ${{ startsWith(github.ref, 'refs/tags/v') }}
-          then
-            if ${{ github.actor != 'dependabot[bot]' }}
-            then
-              if ${{ github.event.release.target_commitish == 'main' && github.event.release.release == true }}
-              then
-                echo "RELEASE=true" >> $GITHUB_ENV
-              elif ${{ github.event.release.prerelease == true }}
-              then
-                echo "PRE_RELEASE=true" >> $GITHUB_ENV
-              fi
-            fi
-          fi
-
-      - name: 🛑 Exit if release or prerelease is not set
-        if: ${{ env.RELEASE != 'true' ||  env.PRE_RELEASE != 'true' }}
-        run: exit 1
+      - name: 💃🕺 Check if release or prerelease
+        run: ./.github/scripts/get-release.sh
+        env:
+          GITHUB_REF: ${{ github.ref }}
+          GITHUB_ACTOR: ${{ github.actor }}
+          GITHUB_COMMITISH: ${{ github.event.release.target_commitish }}
+          GITHUB_RELEASE: ${{ github.event.release.release }}
+          GITHUB_PRE_RELEASE: ${{ github.event.release.prerelease }}
 
       - name: 🏷 Get and Set Package Version on Env
         run: |
@@ -46,10 +35,10 @@ jobs:
             GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)
             SEMVER_VERSION=$(npx find-versions-cli v0.5.5-test123)
             VALID_SEMVER_VERSION=$(echo $SEMVER_VERSION-$GITHUB_SHA_SHORT)
+          el
+            echo "Error: nothing found in environment for REALEASE or PRE_RELEASE"
+            exit 1
           fi
           echo "Semver version $VALID_SEMVER_VERSION"
           echo "VALID_SEMVER_VERSION=$(echo $VALID_SEMVER_VERSION)" >> $GITHUB_ENV
-
-      - name: 🛑 Exit if VALID_SEMVER_VERSION is not set
-        if: ${{ env.VALID_SEMVER_VERSION == "" }}
-        run: exit 1
+          echo "VALID_SEMVER_VERSION saved in environments: ${{ env.VALID_SEMVER_VERSION }}"
